services:
  -type: web
  name: rever-backend
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:

    -key: REDIS_HOST
    sync: false

    -key: REDIS_PORT
    sync: false

    -key: REDIS_USER
    sync: false

    -key: REDIS_PASSWORD
    sync: false